MONGODB_CONNECTION_STRING = ""

MONGODB_DATABASE_WAREHOUSE_ITEMS = ""
MONGODB_DATABASE_WAREHOUSE_USERS = ""
MONGODB_DATABASE_WAREHOUSE_CATEGORIES = ""
MONGODB_DATABASE_WAREHOUSE_TRANSACTIONS = ""
MONGODB_DATABASE_WAREHOUSE_SUPPLIERS = ""
MONGODB_DATABASE_WAREHOUSE_DESTINATIONS = ""



MONGODB_COLLECTION_ITEMS = ""
MONGODB_COLLECTION_USERS = ""
MONGODB_COLLECTION_CATEGORIES = ""
MONGODB_COLLECTION_ITEMS_DETAILS = ""
MONGODB_COLLECTION_TRANSACTIONS = ""
MONGODB_COLLECTION_SUPPLIERS = ""
MONGODB_COLLECTION_SESSIONS = ""
MONGODB_COLLECTION_DESTINATIONS = ""